[1단계 - 로또] 김경근 미션 제출합니다.
hongik-dev-mentoring/java-lotto pull request #1
Opened 2023-02-09 18:12 UTC by JuneK3

2023-02-12 12:03 UTC, dongho108 requested changes
안녕하세요 경근님~ 로또 미션 어려웠을텐데 고생 많으셨습니다!

몇가지 코멘트 남겼는데 반영해주시고 다시 리뷰요청 해주시면 감사하겠습니다~!

2023-02-12 12:03 UTC, dongho108 commented on src/main/java/controller/LottoController.java
> +        LottoWinningNumbers lottoWinningNumbers = readWinningNumbers();
List를 변수명에 넣지 말아요~ 이유는 사전과제 피드백에도 있습니다~

2023-02-12 12:03 UTC, dongho108 commented on src/main/java/controller/LottoController.java
> +        List<LottoDto> lottoDtoList = new ArrayList<>();
헝가리안 표기법 지양합시다~

2023-02-12 12:03 UTC, dongho108 commented on src/main/java/view/Input.java
> +import domain.LastLottoNumbers;
view에서 도메인 패키지를 직접 의존하고 있네요 뷰와 도메인을 분리합시다~

2023-02-12 12:03 UTC, dongho108 commented on src/main/java/domain/BonusNumber.java
> +        int bonusNumber = checkInputFormat(input);
도메인에서 `input`을 알아야할까요? 그리고 BonusNumber가 input을 숫자로 변경하는 책임까지 있어야 할까요?

2023-02-12 12:03 UTC, dongho108 commented on src/main/java/domain/InputPrice.java
> +    private final int price;
도메인에서 Input을 알아야할까요?

2023-02-12 12:03 UTC, dongho108 commented on src/main/java/domain/InputPrice.java
> +            throw new IllegalArgumentException("구입금액은 1000원 이상이어야 합니다.");
매직넘버~

2023-02-12 12:03 UTC, dongho108 commented on src/main/java/domain/LastLottoNumbers.java
> +        List<Integer> lastLottoNumbers = checkInputFormat(input);
여기도 도메인이 input을 변환하는 책임까지 가져야 할까요?

2023-02-12 12:03 UTC, dongho108 commented on src/main/java/domain/LottoChecker.java
> +        resultMap.put(FIRST_PRIZE.getPrizeKey(), INITIAL_COUNT);
Map의 구현체중에서 TreeMap을 사용하신 이유가 있을까요?

2023-02-12 12:03 UTC, dongho108 commented on src/main/java/domain/LottoDto.java
> +    }
이건 어떨까요?
```suggestion
        this.lottoNumbers = lottoNumbers;
```

2023-02-12 12:03 UTC, dongho108 commented on src/main/java/domain/LottoNumberCounter.java
> +    private final LottoWinningNumbers lottoWinningNumbers;
해당 변수는 인스턴스 변수로 있을 필요가 없을 것 같아요. 충분히 메서드로도 판별이 가능해 보입니다!

2023-02-12 12:03 UTC, dongho108 commented on src/main/java/domain/LottoNumberCounter.java
> +    }
`hasBonusNumber`가 메서드로 빠진다면 이 두 메서드에서 중복을 없앨 수 있을 것 같아요.

2023-02-12 12:03 UTC, dongho108 commented on src/main/java/domain/LottoNumberCounter.java
> +    }
테스트에서만 쓰이는 메서드에요~ 제거해주세요!

2023-02-12 12:03 UTC, dongho108 commented on src/main/java/domain/LottoNumberCounter.java
> +    }
얘도 테스트에서만 쓰이고 있네요~ 전체적으로 테스트에서만 쓰이고 있는 메서드라면 제거해보아요

2023-02-12 12:03 UTC, dongho108 commented on src/main/java/domain/LottoPrize.java
> +    NO_PRIZE("NO_PRIZE", "꽝", 0);
prizeText는 도메인이 뷰에 의존하는것처럼 보이는데 경근님 생각은 어떠신가요?

2023-02-12 12:03 UTC, dongho108 commented on src/main/java/domain/LottoPrize.java
> +    }
사용이 안되고 있는 메서드들이네요! getter를 미리 만들어놓는 습관은 없애고 getter를 지양하는 연습을 해보아요

2023-02-12 12:03 UTC, dongho108 commented on src/main/java/domain/LottoWinningNumbers.java
> +    }
getter로 꺼내지 않고 메세지를 보내볼 수 있을 것 같아요

2023-02-12 12:03 UTC, dongho108 commented on src/main/java/view/Input.java
> +
public으로 지정하신 이유가 있을까요?

2023-02-12 12:03 UTC, dongho108 commented on src/main/java/view/Input.java
> +
변수명 축약은 지양합시다~
```suggestion
    public final Scanner scanner = new Scanner(System.in);
```

2023-02-12 12:03 UTC, dongho108 commented on src/main/java/view/Input.java
> +    public final Scanner sc = new Scanner(System.in);
ResultView는 static으로 선언하셨는데 Input은 static으로 하지 않으신 이유가 있을까요?

2023-02-12 12:03 UTC, dongho108 commented on src/test/java/domain/BonusNumberTest.java
> +    public void handleBonusNumberFormatTest() {
이 테스트의 테스트케이스에는 영어 대소문자, 특수문자 등이 있을 것 같아요~ 테스트케이스를 더 추가해주세요!

2023-02-12 12:03 UTC, dongho108 commented on src/test/java/domain/BonusNumberTest.java
> +    @DisplayName("보너스 번호 범위 예외 테스트")
이런 범위 테스트는 경계값들을 테스트 해주셔야 하는데요~ 최소한 `0, 1, 45, 46` 의 테스트는 있어야 할 것 같습니다!

2023-02-12 12:03 UTC, dongho108 commented on src/test/java/domain/InputPriceTest.java
> +    }
여기도 테스트 케이스르 추가해주세요~

2023-02-12 12:03 UTC, dongho108 commented on src/test/java/domain/LastLottoNumbersTest.java
> +    }
전체적으로 테스트케이스들을 추가해주셔야겠네요~

2023-02-12 12:03 UTC, dongho108 commented on src/test/java/domain/LottoGeneratorTest.java
> +    }
Assertions 는 static import를 해주시면 더 깔끔해집니다~
다른 코드들도 static import로 바꿔주세요!

```suggestion
        assertThat(lottoDto.getLottoNumbers().size()).isEqualTo(6);
```

2023-02-12 12:03 UTC, dongho108 commented on src/test/java/view/InputTest.java
> +    @Test
입출력에 대한 부분은 테스트하지 않아도 된다고 요구사항에 추가해주었어요~ 그래도 이미 작성해주셨으니 남겨놔도 좋고 지우셔도 좋습니다!

2023-02-14 01:17 UTC, JuneK3 commented on src/main/java/controller/LottoController.java
> +        LottoWinningNumbers lottoWinningNumbers = readWinningNumbers();
이전 과제에서도 지적받았던 것 같은데 수정하겠습니다.
사전과제 공통 피드백도 다시 읽어볼게요.

2023-02-14 01:26 UTC, JuneK3 commented on src/main/java/controller/LottoController.java
> +        List<LottoDto> lottoDtoList = new ArrayList<>();
lottoDtoGroup으로 수정했습니다.

2023-02-14 01:36 UTC, JuneK3 commented on src/main/java/domain/LottoChecker.java
> +        resultMap.put(FIRST_PRIZE.getPrizeKey(), INITIAL_COUNT);
```java
public static void printStatistics(Map<String, Integer> lottoStatistics) {
        System.out.println("당첨 통계");
        System.out.println("---------");
        for (Map.Entry<String, Integer> lottoEntry : lottoStatistics.entrySet()) {
            LottoPrize lottoPrize = LottoPrize.valueOf(lottoEntry.getKey());
            System.out.println(lottoPrize.getPrizeText() + "- " + lottoEntry.getValue() + "개");
        }
    }
```
로또 통계를 출력할때 5등부터 출력하기 위해서는 map을 정렬해야 할 것 같더라구요.
정렬기능을 적용할 수 있는 map에 TreeMap이 있어서 사용했던 것 같습니다.
근데 mapkey에 enum을 도입하고 리팩토링하면서 mapkey로 정렬되는 부분이 유효하지 않게 되었네요..
정렬될 수 있도록 다시 수정해야 할 것 같아요.

TreeMap을 사용하지 않고 Map을 List로 변환한 후에 정렬하는 방법도 괜찮은 것 같아요.
페어 프로그래밍을 하면서 태순님과 어떤 방식으로 구현할지 논의했는데 TreeMap을 사용하는 쪽이 더 간결한 것 같아서 선택하게 되었습니다.

2023-02-14 01:38 UTC, JuneK3 commented on src/main/java/domain/LottoDto.java
> +    }
자동차 경주 미션에서 방어적 선언을 적용하라는 피드백이 있어서 적용해봤습니다.
제 코드가 방어적 선언을 사용하기에 알맞은 상황이 아닌걸까요??
좀 더 고민해보겠습니다.

2023-02-14 01:39 UTC, JuneK3 commented on src/main/java/domain/InputPrice.java
> +            throw new IllegalArgumentException("구입금액은 1000원 이상이어야 합니다.");
바로 수정하겠습니다.

2023-02-14 01:51 UTC, JuneK3 commented on src/main/java/domain/LottoNumberCounter.java
> +    private final LottoWinningNumbers lottoWinningNumbers;
LottoWinningNumbers를 말씀하신게 맞을까요??
확실히 메소드에 매개변수로 넘겨주는 걸로 해결할 수 있어서 인스턴스 변수로 존재해야 할 필요는 없는 것 같아요.
바로 수정해보겠습니다.

2023-02-14 02:01 UTC, JuneK3 commented on src/test/java/domain/LottoGeneratorTest.java
> +    }
바로 수정하겠습니다.

2023-02-14 02:07 UTC, JuneK3 commented on src/main/java/view/Input.java
> +
안좋은 습관으로 굳어진 것 같아요. 바로 수정하겠습니다.

2023-02-14 02:08 UTC, JuneK3 commented on src/main/java/view/Input.java
> +
이 부분은 제 부주의로 놓친 것 같아요. private으로 지정하는게 맞는 것 같습니다.

2023-02-14 02:20 UTC, way4425 commented on src/main/java/view/Input.java
> +    public final Scanner sc = new Scanner(System.in);
Input 메소드들을 static으로 작성하면 InputTest에서 No line found 에러가 발생하더라구요.
이 에러를 피하려고 static을 제거했던 것 같아요.
생각해보니 테스트코드 때문에 메인 로직을 수정하게 된 상황인데다가 input과 관련된 부분은 테스트 코드를 작성하지 않아도 되는 거라 static으로 변경하는게 맞는 것 같습니다.

Scanner를 사용할때마다 생성해줘야 하는건지 아니면 static final로 두어도 괜찮은 건지 판단이 잘 안되더라구요.
혹시 이 부분과 관련된 조언을 들을 수 있을까요?
그리고 static final의 경우에 왜 input 테스트코드를 통과하지 못했던 건지도 궁금합니다.. 이 부분은 스스로 답을 찾기가 힘들더라구요.

2023-02-14 02:24 UTC, JuneK3 commented on src/test/java/view/InputTest.java
> +    @Test
InputTest는 지우는게 나을 것 같아요.
그래도 예외 처리 부분은 남겨두겠습니다.

2023-02-14 03:24 UTC, JuneK3 commented on src/main/java/view/Input.java
> +import domain.LastLottoNumbers;
생각해보니 도메인에서 input을 받아와 도메인 객체로 변환하는 로직은 도메인과 view를 분리하지 못하는 것 같아요.
도메인과 view를 분리하는 방식에 대해서 좀 더 고민해보겠습니다.

2023-02-14 03:29 UTC, JuneK3 commented on src/main/java/domain/InputPrice.java
> +    private final int price;
도메인에서 Input을 알아야 하는 시점에서 객체간의 책임이 제대로 분리되지 않은 것 같아요.
각 도메인에서 예외처리를 담당하게 하려는 의도로 이렇게 작성했는데 좀 더 고민해봐야 할 것 같아요.
일단 도메인과 input 관련 로직을 분리해보겠습니다.

2023-02-14 03:29 UTC, JuneK3 commented on src/main/java/domain/BonusNumber.java
> +        int bonusNumber = checkInputFormat(input);
BonusNumber가 input을 받아와 숫자로 변경하게 되면 view를 의존한다고 볼 수 있을 것 같아요.
숫자로 변경하는 로직은 Input관련 객체에 위치해야 할 것 같습니다.

2023-02-14 03:31 UTC, JuneK3 commented on src/main/java/domain/LastLottoNumbers.java
> +        List<Integer> lastLottoNumbers = checkInputFormat(input);
각 도메인에서 예외처리를 담당하도록 하는게 괜찮은 방식이라고 생각했는데 좀 더 고민해봐야 할 것 같아요.
일단 도메인과 예외처리를 분리해보겠습니다.

2023-02-14 03:37 UTC, JuneK3 commented on src/main/java/domain/BonusNumber.java
> +        int bonusNumber = checkInputFormat(input);
InputView에서는 input과 관련된 view를 담당하게 하고 input을 도메인 객체로 변환하는 책임을 InputParser가 수행하도록 하면 어떨까요? InputParser에서 input에 대해 예외처리를 거치고 도메인 객체로 변환하도록 하면 도메인 객체가 view 로직이 아닌 InputParser를 의존하게 되니까 view와 도메인 객체를 분리할 수 있을 것 같아요.

콘솔에 출력하는 로직이 아니기 때문에 InputParser가 view 로직이 아니라고 생각했는데 InputParser도 view 로직에 해당될지 고민되네요. 일단 수정해보겠습니다.

2023-02-14 07:12 UTC, JuneK3 commented on src/main/java/domain/LottoNumberCounter.java
> +    }
넵 수정하겠습니다.

2023-02-14 07:14 UTC, JuneK3 commented on src/main/java/domain/LottoNumberCounter.java
> +    }
```java
lottoWinningNumbers.isBonusNumber(number)
``` 
위의 조건식을 메소드로 분리해서 countLottoNumbers 메소드로 보너스 번호까지 카운트 할 수 있도록 변경했습니다.
제가 변경한 방식이 의도하신 부분이 맞는지 모르겠네요..

2023-02-14 07:26 UTC, JuneK3 commented on src/main/java/domain/LottoPrize.java
> +    }
ResultView에서 호출하고 있어서 바로 제거하기는 힘들것 같아요.
getter를 안쓰는 방식을 좀 더 고민해볼게요.

2023-02-14 07:26 UTC, JuneK3 commented on src/main/java/domain/LottoWinningNumbers.java
> +    }
바로 수정해보겠습니다.

2023-02-14 07:28 UTC, JuneK3 commented on src/main/java/domain/LottoNumberCounter.java
> +    private final LottoWinningNumbers lottoWinningNumbers;
```java
public String decideLottoPrize() {
        if (count == 3) {
            return PRIZE_5TH.getPrizeKey();
        }
        if (count == 4) {
            return PRIZE_4TH.getPrizeKey();
        }
        if (count == 5 && hasBonusNumber) {
            return PRIZE_2ND.getPrizeKey();
        }
        if (count == 5) {
            return PRIZE_3RD.getPrizeKey();
        }
        if (count == 6) {
            return PRIZE_1ST.getPrizeKey();
        }
        return NO_PRIZE.getPrizeKey();
    }
```
위의 메소드에서 hasBonusNumber 값을 필요로해서 바로 제거하기가 힘드네요..
일단 인스턴스 변수로 남겨두고 좀 더 고민해보겠습니다.

2023-02-14 07:46 UTC, JuneK3 commented on src/test/java/domain/BonusNumberTest.java
> +    public void handleBonusNumberFormatTest() {
테스트케이스가 많이 부실한 것 같네요.. 좀 더 보충해보겠습니다.

2023-02-14 07:46 UTC, JuneK3 commented on src/test/java/domain/BonusNumberTest.java
> +    @DisplayName("보너스 번호 범위 예외 테스트")
이 부분도 보충해보겠습니다.

2023-02-14 08:07 UTC, JuneK3 commented on src/test/java/domain/LastLottoNumbersTest.java
> +    }
넵 바로 수정하겠습니다.

2023-02-14 08:07 UTC, JuneK3 commented on src/test/java/domain/InputPriceTest.java
> +    }
넵 알겠습니다.

2023-02-14 08:23 UTC, JuneK3 commented on src/main/java/domain/LottoNumberCounter.java
> +    }
getCount가 존재해야만 테스트를 검증할 수 있다고 생각했는데 다른 메소드로 검증이 가능할 것 같습니다.
바로 수정해볼게요.

2023-02-14 08:26 UTC, way4425 commented on src/main/java/domain/LottoPrize.java
> +    NO_PRIZE("NO_PRIZE", "꽝", 0);
확실히 prizeText는 view 로직에 해당한다고 생각해요.
enum은 도메인로직이 아니라고 생각해서 이렇게 작성했던 것 같아요.
prizeText를 enum에서 분리해보겠습니다.

2023-02-16 01:43 UTC, dongho108 commented on src/main/java/controller/LottoController.java
> +        ResultView.printLottoNumbers(lottoDtoGroup);
개인적인 의견이지만 Group이라는 단어도 어떤 의미로 쓰일 수 있기 때문에 저는 리스트나 복수면 s를 붙이는 것을 선호합니다. ㅎ
```suggestion
        List<LottoDto> lottoDtos = LottoGenerator.generateLottos(purchaseNum);
        List<LottoDto> lottosDto = LottoGenerator.generateLottos(purchaseNum);
```

2023-02-16 01:43 UTC, dongho108 commented on src/main/java/controller/LottoController.java
> +            return getInputPrice();
예외메세지도 컨트롤러에서 호출하기보단 OutputView를 이용해 호출해야할 것 같아요!
컨트롤러의 역할은 domain, view를 호출해주는 역할이지 view를 직접 출력하는 역할은 아니니까요!

2023-02-16 01:43 UTC, dongho108 commented on src/main/java/domain/BonusNumber.java
> +        int bonusNumber = checkInputFormat(input);
상당히 좋은 고민을 하고 계시네요 ㅎㅎ 💯 
예외처리도 사실 두가지 경우가 있을 것 같은데요!

1. input을 숫자로 변환하는 것 자체에서 발생하는 예외
2. 해당 숫자가 도메인 규칙에 맞지 않는 예외

각 예외가 어느 부분의 책임인지 생각하시면 더 쉬워질 수 있습니다!
그리고 고민되는 부분은 DM으로 물어보셔도 돼요 ㅎㅎ

2023-02-16 02:16 UTC, dongho108 requested changes
안녕하세요 경근님! 로또 1단계 하느라 고생 많으셨어요!!
로또 미션이 굉장히 어려운 미션인거 저도 알고있습니다 ㅎㅎ;
저도 작년에 진행할때 많이 어려웠었거든요. 그런데 객체에 대한 고민을 그만큼 많이할 수록 객체의 책임을 어디에 어떻게 줄 것인가를 점점 알게되는 것 같아요.

원래는 1단계를 머지하려 했으나, 2단계와 함께 진행하기엔 버거울 수 있을 것 같아서 한번 더 request change를 드리겠습니다!

parser로 나누시고 검증에 대한 고민을 하고계신데, 제가 코멘트 달아드린것 확인하시고 이해 안되시면 디엠 주시면 다시 설명드리겠습니다!

화이팅 :)

2023-02-16 02:16 UTC, dongho108 commented on src/main/java/domain/LottoGenerator.java
> +    public static final int NUMBER_OF_LOTTO_NUMS = 6;
45라는 숫자를 들고있는 객체들이 많은데요, 책임이 적절히 위임이 되어있지 않고 분산되어있다는 의미로 보입니다!
1~45 규칙이 있는 LottoNumber 라는 객체를 통해 해결해볼 수 있을까요?

2023-02-16 02:16 UTC, dongho108 commented on src/main/java/domain/LottoGenerator.java
> +    }
클래스 이름은 `LottoGenerator`이고, 메서드이름도 `generateLottos` 인데 반환은 `List<LottoDto>`를 반환하고 있네요!
그리고 해당 메서드는 사용이 되지 않고있어요!

2023-02-16 02:16 UTC, dongho108 commented on src/main/java/domain/LottoNumberCounter.java
> +        int count = countLottoNumbers(dto);
도메인에서 dto를 의존하고 있다는 것도 view에 의존한다고 볼 수 있지 않을까요?
view의 스펙이 바뀌면 dto도 바뀔거고, 도메인도 바뀌니까요!
dto를 변환하거나 사용하는 로직은 domain에 있으면 안될것 같아요!

2023-02-16 02:16 UTC, dongho108 commented on src/main/java/parser/BonusNumberParser.java
> +
parser에게서 도메인 요구사항에 대한 검증까지 있기보단, parser에선 input에 대한 parse만 하고 BonusNumber 안에서 도메인 요구사항 (1~45 등)의 검증이 있으면 좋을 것 같아요!

2023-02-17 07:10 UTC, JuneK3 commented on src/main/java/controller/LottoController.java
> +        ResultView.printLottoNumbers(lottoDtoGroup);
확실히 변수명에 group이 들어가는 것보다 s를 붙이는게 나은 것 같아요. 수정해보겠습니다.

2023-02-17 07:10 UTC, JuneK3 commented on src/main/java/controller/LottoController.java
> +            return getInputPrice();
말씀하신 부분이 맞는 것 같아요. 이 부분도 ResultView가 담당하도록 변경해보겠습니다.

2023-02-17 08:18 UTC, JuneK3 commented on src/main/java/domain/LottoGenerator.java
> +    public static final int NUMBER_OF_LOTTO_NUMS = 6;
LottoNumber 객체를 도입하면 parser에서 동일하게 숫자 범위를 체크하는 로직을 제거할 수 있을 것 같아요.
LottoGenerator는 input을 받아서 LottoNumber 객체를 생성하는 케이스가 아니라서 숫자 45를 들고 있어야 할 것 같습니다. 더 좋은 방식이 있는지 계속 고민해 보겠습니다.

2023-02-17 08:24 UTC, JuneK3 commented on src/main/java/domain/LottoNumberCounter.java
> +        int count = countLottoNumbers(dto);
dto를 view에서만 의존하도록 변경하겠습니다.
도메인 로직에서는 dto를 변환하는 로직이 있으면 안될 것 같아요.
dto 도입에 대해 좀 더 고민해 보겠습니다. 너무 생각없이 코드를 작성한 것 같아요.

2023-02-17 08:27 UTC, JuneK3 commented on src/main/java/parser/BonusNumberParser.java
> +
확실히 parser에선 input에 대한 검증만 하는게 나을 것 같아요. LottoNumber 도메인을 생성한 상태라 BonusNumber 도메인을 추가로 생성할지 고민이 되네요.. 일단 BonusNumber도 LottoNumber에 해당한다고 생각해서 BonusNumber 도메인을 추가로 만들지는 않았습니다.

2023-02-17 11:05 UTC, JuneK3 commented on src/main/java/domain/LottoGenerator.java
> +    }
lottoDto가 아닌 도메인 객체를 생성하는 방식으로 변경했습니다.

2023-02-17 11:12 UTC, JuneK3 commented
### 2/17

리뷰해주신대로 input parse 관련 예외처리는 parser가 맡도록 하고 도메인 관련 예외처리는
도메인 객체들을 추가해서 담당하도록 변경했습니다.
읽기 쉬운 코드를 작성하고 싶었는데 제가 읽기에도 이해하기 쉬운 느낌이 안드네요..

2023-02-18 09:05 UTC, dongho108 commented on src/main/java/domain/LottoChecker.java
> +        resultMap.put(FIRST_PRIZE.getPrizeKey(), INITIAL_COUNT);
ㅎㅎ 잘못사용했다고 말씀드린건 아니었고 사용하신 구현체의 특징을 잘 알고 사용하셨나 생각해서 리뷰남겨봤습니다~ 💯

2023-02-18 09:08 UTC, dongho108 commented on src/main/java/domain/LottoPrize.java
> +    }
아 ResultView에서 호출하고있다면 사용하고있는 것이니 제거는 안하셔도 됩니다 ㅎㅎ
제가 리뷰하는 시점에 잘못봤었나보네요!

2023-02-18 09:22 UTC, dongho108 commented on src/main/java/view/Input.java
> +    public final Scanner sc = new Scanner(System.in);
`Scanner를 사용할때마다 생성해줘야 하는건지 아니면 static final로 두어도 괜찮은 건지 판단이 잘 안되더라구요.`

static으로 선언하면 여러 스레드에서 해당 자원을 공유하게 됩니다.
하지만 매번 생성되지 않고 한번만 생성할 수 있습니다.

해당 Input 클래스가 초당 100만개의 요청을 처리한다고 가정해봅시다.
static으로 선언시에는 최초 한번만 생성하면 됩니다.
하지만 요청당 scanner를 매번 생성한다면 낭비가 되겠죠.

그렇다면 항상 static으로 선언했을때 문제가 없을까요?

'해당 자원을 공유해서 사용하면 안될 때' static을 사용하면 문제가 됩니다.
해당 자원이 인스턴스마다 상태를 가져야하는 객체일때, 여러 스레드에서 해당 상태를 변경한다면 각자의 스레드에서 잘못된 값을 읽을 위험이 있습니다.

하지만 경근님이 Input에서 사용중인 scanner는 `상태를 가지고 있지 않고` 그냥 콘솔에서 인풋을 받기위한 용도로 사용됩니다.
그렇다면 여러 스레드에서 공유해서 사용이 가능한 클래스이기 때문에 static으로 사용해도 문제가 없을 것 같아요 ㅎ

추가로 하나 질문을 드리자면,
Java에서 출력할때 StringBuilder를 사용한다면 static으로 선언해도 될까요? 안될까요? 이유와 함께 달아주세요 ㅎ

2023-02-18 09:27 UTC, dongho108 approved these changes
경근님 로또 1단계 미션하느라 정말 고생 많으셨습니다!!!!
이번 미션 정말 고민할 것도 많고, 리뷰도 많고, 요구사항도 어려웠을텐데요
그래도 계속 고민하고 발전해나가시는 과정이 좋았습니다.

1단계는 여기서 마무리하고, 2단계에서 뵙겠습니다!
고생하셨어요~

2023-02-18 09:27 UTC, merged

2023-02-18 09:36 UTC, JuneK3 commented on src/main/java/view/Input.java
> +    public final Scanner sc = new Scanner(System.in);
StringBuilder를 static으로 선언해서는 안될것 같아요.
static으로 선언해 StringBuilder를 공유하게 된다면 의도하지 않은 문자열을 생성할 수도 있을 것 같아요.
자세한 설명 감사합니다. Scanner 선언과 관련된 궁금증을 쉽게 설명해주셔서 이해하기 쉬웠습니다.