[1단계 - 로또] 이태순 미션 제출합니다.
hongik-dev-mentoring/java-lotto pull request #2
Opened 2023-02-10 02:52 UTC by LTSGOD

2023-02-11 06:29 UTC, skullkim requested changes
태순님 안녕하세요~. 첫 페어 프로그래밍은 어떠셨나요? 우선 부분적인 피드백을 남겨봤어요~. 이 피드백들을 반영해 주시면 추가 피드백 들릴게요~

2023-02-11 06:29 UTC, skullkim commented on src/test/java/domain/LottoCheckerTest.java
> +
의미 없는 공백은 제거해 주세요~. 이런 사소한 부분이 쌓이고 쌓여서 깔끔하지 못한 코드가 만들어져요!

2023-02-11 06:29 UTC, skullkim commented on src/test/java/domain/LottoCheckerTest.java
> +    }
유닛 테스트는 통상적으로 given-when-then 구조를 따르는대요(given-when-then은 이 [글](https://martinfowler.com/bliki/GivenWhenThen.html)을 읽어보세요~). 하나의 테스트에서 given, whe, then을 어느 정도는 명확히 구문해 줘야 테스트를 읽기 편해져요. 하지만 이 코드는 given과 when의 경계를 나누지 않았네요. 이 경계는 주석으로 나눌 수 있어요.
```suggestion
    void calculateLottoStatistics() {
        // given
        List<LottoDto> lottoDtoList = new ArrayList<>();
        lottoDtoList.add(new LottoDto(List.of(1, 2, 3, 4, 5, 6)));
        lottoDtoList.add(new LottoDto(List.of(1, 2, 3, 4, 7, 8)));
        lottoDtoList.add(new LottoDto(List.of(1, 2, 3, 4, 5, 8)));
        List<Integer> lastLottoNumbers = List.of(1, 2, 3, 4, 5, 6);
        Integer bonusNumber = 7;
        LottoWinningNumbers lottoWinningNumbers = new LottoWinningNumbers(lastLottoNumbers, bonusNumber);
        LottoChecker lottoChecker = new LottoChecker(lottoDtoList, lottoWinningNumbers);
        // when
        Map<String, Integer> resultMap = lottoChecker.calculateLottoStatistics();
       // then
        Assertions.assertThat(resultMap.get("PRIZE_1ST")).isEqualTo(1);
        Assertions.assertThat(resultMap.get("PRIZE_2ND")).isEqualTo(1);
        Assertions.assertThat(resultMap.get("PRIZE_3RD")).isEqualTo(1);
        Assertions.assertThat(resultMap.get("PRIZE_4TH")).isEqualTo(0);
        Assertions.assertThat(resultMap.get("PRIZE_5TH")).isEqualTo(0);

    }
```
저 같은 경우 주석으로 given-when-then 부분을 표시하지는 않더라도 중간에 공백을 주어서 가독성을 높이는 편이에요.
```suggestion
    void calculateLottoStatistics() {
        List<LottoDto> lottoDtoList = new ArrayList<>();
        lottoDtoList.add(new LottoDto(List.of(1, 2, 3, 4, 5, 6)));
        lottoDtoList.add(new LottoDto(List.of(1, 2, 3, 4, 7, 8)));
        lottoDtoList.add(new LottoDto(List.of(1, 2, 3, 4, 5, 8)));
        List<Integer> lastLottoNumbers = List.of(1, 2, 3, 4, 5, 6);
        Integer bonusNumber = 7;
        LottoWinningNumbers lottoWinningNumbers = new LottoWinningNumbers(lastLottoNumbers, bonusNumber);
        LottoChecker lottoChecker = new LottoChecker(lottoDtoList, lottoWinningNumbers);
        
        Map<String, Integer> resultMap = lottoChecker.calculateLottoStatistics();

        Assertions.assertThat(resultMap.get("PRIZE_1ST")).isEqualTo(1);
        Assertions.assertThat(resultMap.get("PRIZE_2ND")).isEqualTo(1);
        Assertions.assertThat(resultMap.get("PRIZE_3RD")).isEqualTo(1);
        Assertions.assertThat(resultMap.get("PRIZE_4TH")).isEqualTo(0);
        Assertions.assertThat(resultMap.get("PRIZE_5TH")).isEqualTo(0);
    }
```
하나의 메서드에서 코드가 길어 질 때, 코드의 의도를 적절히 나누고, 그 사이에 공백을 주는 것이 가독성을 높이는대 도움이 됩니다😄

2023-02-11 06:29 UTC, skullkim commented on src/main/java/domain/LottoChecker.java
> +    public void updateResult(Map<String, Integer> calculateResult, String mapKey) {
이 메서드를 checkLottoWim()에서만 사용함에도 public으로 열어 둔 이유가 있을까요🧐? 없다면, 불필요하게 넓은 접근이 어떤 분제를 야기할까요?

2023-02-11 06:29 UTC, skullkim commented on src/main/java/domain/LottoChecker.java
> +        if (mapKey.equals(LottoConstant.NO_PRIZE_KEY)) return;
[Google Java Style Guide 4.1.1 Use of Optional braces](https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used) 에 따르면 모든 조건문과 반복문은 하나 이하의 statement만 포함다더라도 '{}'를 사용하는 것을 원칙으로 하고 있는대요.

이 문서에 이렇게 해야 하는 이유가 명확히 나와있지 않아서, 제가 생각하는 이유를 말할게요~.
1. 코드가 명확하지 않다.
- 괄호 없이, 한 줄로 조건을 끝내면, 조건 다음 줄이 해당 조건을 만족 시켰을 때의 로직인지 한 눈에 보기 어려워요. 그에 반해, 괄호를 사용하면 조금 더 명확해 지죠.
2. 유지보수 시 약간의 시간이 더 소모된다.
- 조건문 안에 들어 갈 조건이 두 줄 이상으로 늘어났다고 해볼게요. 그러면 한 줄이었던 조건을 괄호로 묶고, 새로운 조건을 추가해야 되서 시간이 조금 더 걸리겠죠. 개발자는 하루 종일 컴퓨터에 앉아서 키보드를 두드리는 직업이에요. 그 때문에 작업 도중, 동선에서 낭비되는 몇 초의 시간도 쌓이고 쌓이면 큰 격차가 되죠. 그래서 많은 개발자들이 기상천외한 툴들과 온갖 단축키로 그 몇초를 아낄려고 해요. 이 관점에서 괄호를 추가하지 않는다는 것은 비효율적이겠죠?

2023-02-11 06:29 UTC, skullkim commented on src/main/java/domain/LottoChecker.java
> +    private final List<LottoDto> lottoDtoList;
[클린 코드 2장. 의미 있는 이름](https://www.skullkim-dev.com/2022/01/02/2.-%EC%9D%98%EB%AF%B8-%EC%9E%88%EB%8A%94-%EC%9D%B4%EB%A6%84/)을 참고해서 "lottoDtoList"라는 이름에 어떤 문제가 존재하는지 알려주세요~

2023-02-11 06:29 UTC, skullkim commented on src/main/java/domain/LottoConstant.java
> +public class LottoConstant {
이 클래스를 enum을 만들면 조금 더 객체지향적인 코드 작성이 가능할 것으로 보이는대요. 어떤 이유로 enum을 사용하지 않으신거죠?
혹시나, java enum에 대해 잘 모르신다면 다음 글을 참고해 주세요~. [java enum](https://www.skullkim-dev.com/2022/02/21/enum/)

2023-02-11 06:29 UTC, skullkim commented on src/main/java/domain/LottoEnum.java
> +public enum LottoEnum {
"몇개가 일치했을 때의 당첨 금액이 얼마인지"는 도메인이 맞지만, prizeText 자체는 사용자에게 결과를 알려주는 용도이므로 뷰에 해당한다고 보이는대요. 그렇다면 이 부분을 어떻게 수정해야 할까요🧐? 
추가적으로, 이름에 Enum을 붙인 이유가 있을까요? 클래스의 유형이나 변수의 타입을 이름에 명시하는 헝가리안 표기법은 예전에는 좋은 명명법으로 거론되었어요. IDE를 통해 빠르게 타입을 파악할 수 없었기 때문이죠. 하지만, 현대의 IDE는 타입 파악 기능을 잘 제공하고 있어서, 헝가리안 표기법을 사용한 뒤 타입이 바뀔 경우, 변경점만 들어나게 돼요.

2023-02-11 06:29 UTC, skullkim commented on src/main/java/controller/LottoController.java
> +        int purchaseNum = inputPrice / LOTTO_PRICE;
컨트롤러의 역할이 뭘까요🧐? 로또 한 장의 금액은 도메인 로직이 아닐까요? 만약 로또 한 장의 금액도 도메인 로직이라면, 어디에 위치해야 할까요?

2023-02-11 06:29 UTC, skullkim commented on src/main/java/view/ResultView.java
> +            LottoEnum lottoEnum = LottoEnum.valueOf(lottoEntry.getKey());
LottoDto라는 DTO를 만들어서 사용하신 이유를 알 수 있을까요? DTO를 사용하는 이유와 LottoEnum의 사용 간에는 어떤 모순이 존재할까요?

2023-02-11 06:29 UTC, skullkim commented on src/main/java/controller/LottoController.java
> +    private List<LottoDto> generateLottoDtoList(int purchaseNum) {
[클린코드 3장. 함수](https://www.skullkim-dev.com/2022/01/03/3.-%ED%95%A8%EC%88%98/)를 보고 이 메서드에 어떤 문제가 있는지 알려주세요~. 그리고 수정해 주세요

2023-02-11 06:29 UTC, skullkim commented on src/main/java/domain/LottoNumberCounter.java
> +    public String decideLottoPrize() {
이 메서드에서 조건을 줄일 방법이 없을까요? 저희가 진행했던 [자동차 경주게임 프리코스](https://github.com/hongik-dev-mentoring/java-racingcar-precourse) 요구사항에 "else나 swtich를 사용하지 말라"는 조건이 있었는대요. 이 조건이 제시된 근본적인 이유가 뭘까요🧐? 힌트를 드리자면 다형성에 있어요~

2023-02-11 11:29 UTC, dongho108 commented on src/main/java/domain/LottoNumberCounter.java
> +    public String decideLottoPrize() {
로또 요구사항에도 있었답니다

2023-02-12 02:15 UTC, LTSGOD commented on src/test/java/domain/LottoCheckerTest.java
> +
넵 수정하겠습니다!

2023-02-12 02:24 UTC, LTSGOD commented on src/main/java/domain/LottoChecker.java
> +    public void updateResult(Map<String, Integer> calculateResult, String mapKey) {
다른 곳에서 의도치 않게 호출해 설계한 로직이 망가질 수 있겠네요!!

2023-02-12 02:34 UTC, LTSGOD commented on src/main/java/domain/LottoChecker.java
> +    private final List<LottoDto> lottoDtoList;
특수한 의미를 가지는 용어를 남발해서도 안된다. 여러 계정을 그룹으로 묶을때 그 변수의 이름을 accountList라 했다 하자. 여기서 List는 프로그래머에게 특수한 의미를 갖는다. 계정을 담는 컨테이너가 실제 List가 아니라면 대신에 accountGroup 또는 accounts 등으로 명명해야 한다.

List라는 이름이 혼동을 유발할 것 같아요!

2023-02-12 06:37 UTC, JuneK3 commented on src/test/java/domain/LottoCheckerTest.java
> +
넵 알겠습니다.

2023-02-12 06:39 UTC, JuneK3 commented on src/test/java/domain/LottoCheckerTest.java
> +    }
확실히 given, when, then으로 테스트코드를 나눠주면 가독성이 훨씬 좋아질 것 같아요.
이 부분도 반영해서 수정하겠습니다.

2023-02-12 06:42 UTC, JuneK3 commented on src/main/java/domain/LottoChecker.java
> +    public void updateResult(Map<String, Integer> calculateResult, String mapKey) {
이 부분은 private로 작성되어 있어야 하는데 실수로 놓친 것 같아요.
불필요하게 넓은 접근을 허용한다면 제가 작성한 코드에 담긴 의도를 제대로 전달하지 못할 것 같아요.

2023-02-12 06:43 UTC, JuneK3 commented on src/main/java/domain/LottoChecker.java
> +        if (mapKey.equals(LottoConstant.NO_PRIZE_KEY)) return;
확실히 가독성 측면이나 유지보수 측면에서 중괄호로 감싸는게 좋아보이네요.
이 부분도 수정해놓겠습니다.

2023-02-12 06:46 UTC, JuneK3 commented on src/main/java/domain/LottoConstant.java
> +public class LottoConstant {
올려주신 링크 참고해서 enum으로 대체해보겠습니다.

2023-02-12 15:18 UTC, LTSGOD commented on src/main/java/controller/LottoController.java
> +        int purchaseNum = inputPrice / LOTTO_PRICE;
LottoConstant 도메인에 상수로 들어가야할 것같아요!

2023-02-12 15:19 UTC, LTSGOD commented on src/main/java/controller/LottoController.java
> +    private List<LottoDto> generateLottoDtoList(int purchaseNum) {
파라미터 변수가 3개 이상이면 이해하기 어려워 가독성이 떨어지는 것 같네요!

2023-02-12 15:20 UTC, LTSGOD commented on src/main/java/controller/LottoController.java
> +        int purchaseNum = inputPrice / LOTTO_PRICE;
LottoConstant 도메인에 상수로 위치해야할 것같아요!

2023-02-13 13:24 UTC, LTSGOD commented on src/main/java/domain/LottoConstant.java
> +public class LottoConstant {
아 넵 글 참고해서 enum 사용해서 수정하겠습니다!

2023-02-13 14:13 UTC, LTSGOD commented on src/main/java/domain/LottoEnum.java
> +public enum LottoEnum {
뷰에서 처리할 것은 뷰에서 처리하게 분리해서 수정을 한 번 해보겠습니다!

2023-02-14 03:30 UTC, LTSGOD commented on src/main/java/domain/LottoNumberCounter.java
> +    public String decideLottoPrize() {
아 네 고민해보고 코드 수정해보겠습니다!

2023-02-14 05:39 UTC, LTSGOD commented on src/main/java/view/ResultView.java
> +            LottoEnum lottoEnum = LottoEnum.valueOf(lottoEntry.getKey());
Dto 의 개념이 확실하지 않은 상태에서 맞지않을까? 라고 확신없이 작성한 코드 같습니다..!

2023-02-16 06:09 UTC, skullkim requested changes
안녕하세요~ 태순님. 반영해주신 내용 잘 확인했습니다. 피드백에 달아주신 내용을 보다가 든 생각인대요. 제가 어떤 질문을 하거나, 어떤 부분에 수정이 필요하 했을 때 태순님의 의견과 이유를 반드시 적어주세요. 모든 것에는 명확한 이유가 있어야 해요~.

추가로 객체지향에 대한 이해가 아직은 부족한 것 같아요. 이대로 미션을 머지하고 다음 단계로 넘어가는 것은 무의미 한것 같네요. 제가 추가한 피드백을 반영하기 전에 아래 링크에 있는 글들을 정독해 주세요😊. 그 다음에 피드백을 반영해 주세요~.

2023-02-16 06:09 UTC, skullkim commented on src/main/java/domain/LottoNumbers.java
> +public class LottoNumbers {
LottoNumbers는 왜 만드신 건가요? 객체의 핵심이 뭘까요? LottoNumbers는 객체일까요 아니면 자료구조일까요?

2023-02-16 06:09 UTC, skullkim commented on src/main/java/domain/LottoWinningNumbers.java
> +    private final List<Integer> lastLottoNumbers;
로또 당첨 숫자랑 마지막 로또 숫자(lastLottoNumbers)는 어떤 관계가 있는건가요? last라는 단어를 사용한 이유가 있나요?

2023-02-16 06:09 UTC, skullkim commented on src/main/java/view/InputException.java
> +public class InputException {
이 클래스에 있는 검증 로직이 정말 뷰에 존재하는 것이 적절할까요? 뷰랑 도메인의 차이가 뭘까요🧐? 뷰에 이런 로직이 있으면 어떤 문제가 발생할까요?

2023-02-16 06:09 UTC, skullkim commented on src/main/java/view/ResultView.java
> +    public static void printPurchaseInfo(int purchaseNum) {
이 메서드 이름은 어떤 문제가 있을까요?

2023-02-16 06:09 UTC, skullkim commented on src/main/java/controller/LottoController.java
> +    private List<LottoNumbers> lottoNumbersGroupGenerator(int purchaseNum) {
purchaseNum이라는 이름은 어떤 문제를 가지고 있을까요?

2023-02-16 06:09 UTC, skullkim commented on src/main/java/controller/LottoController.java
> +        for (int i = 0; i < purchaseNum; i++) {
컨트롤러는 어떤 역할을 한다고 생각하시나요? "구매한 로또 갯수 만큼 로또를 자동 생성한다" 는 도메인 로직일까요? 아니면 컨트롤러에 넣어야 하는 로직일까요?

2023-02-16 06:09 UTC, skullkim commented on src/main/java/view/ResultView.java
> +            LottoEnum lottoEnum = LottoEnum.valueOf(lottoEntry.getKey());
그럼 DTO는 어떤 용도일까요?

2023-02-16 06:09 UTC, skullkim commented on src/main/java/domain/LottoPrice.java
> +public class LottoPrice {
이게 객체가 맞을까요? LottoPrice가 가져야할 책임은 뭐가 있을까요?

2023-02-16 06:09 UTC, skullkim commented on src/main/java/domain/LottoChecker.java
> +public class LottoChecker {
클래스, 패키지, 변수, 메서드 등 코드 상에 존재하는 모든 것의 이름을 잘 짓는 것이 왜 중요할까요? LottoChecker는 로또의 무엇을 체크하는지 명확히 드러나 있지 않네요. LottoNumberCounter 역시 겉보기에는 로또 숫자를 카운트 해주는 객체라 보이지만, 실제로는 당첨 번호라는 제약 사항이 있네요. 모든 이름은 이름의 대상을 명확히 특정지을 수 있게 지어야 합니다.

로직 상 LottoChecker가 우승에 대한 결과를 연산하고 반환하는 대요. 그렇다면 LottoNumberCounter의 로직도 LottoChecker에 넣을 수 있지 않을까요? 객체를 나누는 이유가 뭘까요? 필드는 어떤 의미를 가질까요?

2023-02-17 02:13 UTC, LTSGOD commented on src/main/java/domain/LottoWinningNumbers.java
> +    private final List<Integer> lastLottoNumbers;
저도 다시 읽는데 왜 last라는 이름으로 지었는지 이해가 되지 않았습니다. winningLottoNumbers로 바꿔서 더 명확히 네이밍 하겠습니다!

2023-02-18 08:42 UTC, merged