[1단계 - 로또] 이진호 미션 제출합니다.
hongik-dev-mentoring/java-lotto pull request #3
Opened 2023-02-10 03:28 UTC by binary-ho

2023-02-13 06:33 UTC, skullkim requested changes
진호님 안녕하세요~. 제가 일정을 잘못 인지해서 리뷰가 살짝 늦어졌네요. 죄송합니다😭. 우선 부분적인 리뷰를 남겼어요~. 이 피드백들을 반영하시고 나면 추가 리뷰를 해드릴게요~.

2023-02-13 06:33 UTC, skullkim commented on src/main/java/view/OutputView.java
> +			.forEach(System.out::println);
```suggestion
		lottoTicketDto.getLottoNumbersDto()
			.forEach(System.out::println);
```
이건 어떨까요🧐? 그리고 stream().forEach()와 .forEach()의 차이는 뭘까요?

2023-02-13 06:33 UTC, skullkim commented on src/main/java/view/OutputView.java
> +		StringBuilder purchaseCountString = new StringBuilder()
String을 사용하지 않고 StringBuilder를 사용한 이유가 있을까요?

2023-02-13 06:33 UTC, skullkim commented on src/main/java/view/OutputView.java
> +		EnumMap<Ranking, Integer> rankingResults = lottoResultDto.getLottoResult();
EnumMap과 HashMap의 차이는 무엇일까요🧐? EnumMap을 사용하면 어떤 이점이 있을까요?

2023-02-13 06:33 UTC, skullkim commented on src/main/java/view/OutputView.java
> +		if (winningAmount == 30000000) {
"30000000"이라는 매직 넘버를 상수로 빼면 코드가 더 명확해지지 않을까요? 그리고 자바의 경우 숫자가 커지면 가독성을 위해 숫자 중간에 '_'를 넣어 단위를 구분할 수 있어요~. 이 부분을 예시로 들면"30_000_000"처럼 표기할 수 있어요!

2023-02-13 06:33 UTC, skullkim commented on src/main/java/controller/LottoController.java
> +	private final int LOTTO_NUMBER_LIMIT = 6;
FROM, TO, LOTTO_NUMBER_LIMIT을 static으로 해놓지 않은 이유가 있을까요?

2023-02-13 06:33 UTC, skullkim commented on src/main/java/controller/LottoController.java
> +	private static final int LOTTO_TICKET_PER_PRICE = 1000;
코드에서 빈 줄은 서로 다른 종류의 코드를 구분짓는 용도로 사용하는대요. privat static final과 private final은 다른 종류의 필드라는 생각이 드네요. 이 부분에 공백을 삽입해야 하지 않을까요? 어떻게 생각하시나요?

2023-02-13 06:33 UTC, skullkim commented on src/main/java/domain/BonusBall.java
> +public class BonusBall {
static class는 어떤 상황에 어떤 이유로 사용하는 것이 적절할까요? BonusBall을 static 클래스로 정의하신 이유는 뭔가요?

2023-02-13 06:33 UTC, skullkim commented on src/main/java/domain/Lotto.java
> +	public static Lotto generateLottoWithLottoNumbers(LottoNumberGenerator lottoNumberGenerator, int numberOfLotto) {
생성자를 private으로 두고 static method로 생성자를 그대로 호출하는 이유가 뭔가요🧐?

2023-02-13 06:33 UTC, skullkim commented on src/main/java/domain/Lotto.java
> +		if (ranking == Ranking.THIRD && lottoNumbers.contains(bonusBall.getBonusBallNumber())) {
조건문의 조건이 길어지면 어떤 의도로 해당 조건을 사용했는지 파악하기 어려워요. 조건 부분만 별도의 메서드로 분리하는 것은 어떤가요?

2023-02-13 06:33 UTC, skullkim commented on src/main/java/domain/LottoNumberGenerator.java
> +	private void shuffleNumbers(List<Integer> numbers) {
혹시 로직을 메서드로 분리하는 이유가 뭐라고 생각하시나요?

2023-02-13 06:33 UTC, skullkim commented on src/main/java/domain/LottoNumbers.java
> +	private static final int LOTTO_NUMBER = 6;
로또의 크기를 의도한 것이라면 LOTTO_NUMBER 대신 LOTTO_SIZE는 어떤가요?

2023-02-13 06:33 UTC, skullkim commented on src/main/java/domain/LottoNumbers.java
> +public class LottoNumbers implements Numbers {
LottoNumbers가 Numbers를 implements 함에도 다른 객체에서 Numbers를 타입으로 사용하는 대신 LottoNumbers를 타입으로 사용하고 있네요. 왜 그렇게 한거죠?

2023-02-13 06:33 UTC, skullkim commented on src/main/java/domain/LottoTicket.java
> +public class LottoTicket {
일급 컬렉션을 사용하는 이유가 뭘까요🧐? 현재 LottoTicket은 아무런 책임을 갖지 않기에 객체가 아닌 자료구조로 사용하고 있는대요. 이런 일급 컬랙션이 필요할까요?

2023-02-13 06:33 UTC, skullkim commented on src/main/java/domain/Ranking.java
> +	public static Ranking getRanking(int correctNumber) {
이 부분을 스트림으로 더 간결하고 명확하게 작성할 수 없을까요?

2023-02-13 06:33 UTC, skullkim commented on src/main/java/domain/WinningNumbers.java
> +public class WinningNumbers implements Numbers {
WinningNumbers 역시 Numbers를 implements 하지만 이를 사용하는 곳에서 타입을 Numbers가 아닌 WinningNumbers로 사용하고 있네요.

2023-02-13 06:33 UTC, skullkim commented on src/main/java/dto/LottoNumbersDto.java
> +		return Numbers.toString();
IntelliJ에서 자동완성으로 주는 toString()을 그대로 사용하지 않고 직접 커스텀한 이유가 있을까요?

2023-02-13 06:33 UTC, skullkim commented on src/main/java/dto/LottoResultDto.java
> +	}
LottoNumbersDto에는 toString()을 재정의 했고, 이 DTO에서는 재정의 하지 않은 이유가 있을까요? java에서 toString을 재정의 해야 하는 이유는 무엇일까요?

2023-02-18 04:31 UTC, binary-ho commented on src/main/java/dto/LottoNumbersDto.java
> +		return Numbers.toString();
Output View에선 LottoTicketDto를 통해 구매한 로또 번호들을 출력합니다.
구매한 각각의 로또 번호들은 LottoTicketDto안의 LottoNumbersDto가 Integer의 리스트의 형태로 가지고 있습니다.
LottoNumbersDto가 가진 Integer 리스트의 숫자들을 출력하려는 상황에서, 
비록 DTO지만 내부의 Integer 리스트를 반환하는 getter를 정의한 다음, getter를 호출한 쪽에서 리스트의 내용물을 출력하게 만들기 보다는 
차라리 단순 내부 필드 출력만을 위한 getter를 없애고, DTO가 내부 Integer 리스트 필드를 직접 출력하도록 하는게 낫다고 생각했습니다. 

위에서 설명한 의도로, LottoNumbersDto의 toString을 커스텀 해주었습니다.
LottoNumbersDto의 클래스명과 해쉬코드 String이 아닌, 내부 필드인 Integer 리스트의 내용물로 만든 String을 반환하도록 커스텀 해주었습니다.

2023-02-18 05:24 UTC, binary-ho commented on src/main/java/domain/LottoNumberGenerator.java
> +	private void shuffleNumbers(List<Integer> numbers) {
분리할 당시에는 래핑된 코드만 보고 무엇을 하는지 명확하지 않을 수도 있겠다는 생각에 위와 같이 분리했습다.
다시 보니 그럴 필요가 없어 보입니다. 감사합니다!

2023-02-18 05:27 UTC, binary-ho commented on src/main/java/domain/BonusBall.java
> +public class BonusBall {
BonusBall을 static class로 구현한 이유는 정적 팩터리 메서드를 통해 객체를 만들게 하고 싶어서 입니다. 그 과정에서 정적 팩터리 메서드에서 호출되는 메서드들이 static으로 선언 되었습니다.

정적 팩터리 메서드를 사용한 이유는 BonusBall을 생성할 때 범위나 중복에 대한 검증 책임을 부여하고 싶었는데, 단순히 BounsBall()과 같은 생성자만을 사용한다면, 
호출하는 쪽에서 생성자에 범위나 당첨 번호가 들어가는 상황에서, 이 인수들이 왜 들어가야 하고, 어떻게 쓰이는지 짐작하기가 어려울 것 같아, 생성자에 이름을 부여하고 싶은 마음에 사용했습니다.

2023-02-18 05:31 UTC, binary-ho commented on src/main/java/domain/Lotto.java
> +	public static Lotto generateLottoWithLottoNumbers(LottoNumberGenerator lottoNumberGenerator, int numberOfLotto) {
Lotto 객체를 만들 때, 생성자에 LottoGenerator와 구매 갯수를 넣는 이유를 알면 좋을것 같아 정적 팩터리 메서드를 이용해 보았습니다!

2023-02-18 05:34 UTC, binary-ho commented on src/main/java/domain/LottoNumbers.java
> +public class LottoNumbers implements Numbers {
LottoNumbers와 LottoWinningNumbers 는 대동소이합니다. 
Integer 리스트 필드를 가지며, 검증 책임들을 갖습니다.
이에 추상화를 하고 싶어 인터페이스로 만들었는데, 
말씀 주신 부분과 함께 곰곰이 생각해보니 추상 클래스로 구현하는 것이 더 적절해 보인다는 생각이 듭니다.
감사합니다!

2023-02-18 05:40 UTC, binary-ho commented on src/main/java/domain/LottoTicket.java
> +public class LottoTicket {
LottoTicket은 우리가 평소에 5천원 어치 로또를 사면 나오는 로또 용지를 생각하며 만들었습니다.
실제 로또 용지와 같이 한줄 한줄의 구매 로또 번호를 의미하는 LottoNumbers를 리스트로 가지고 있습니다.
LottoNumbers 리스트에 불변성을 부여하고, 이름을 부여하고자 일급 컬랙션으로 구현해 보았습니다!

2023-02-18 05:41 UTC, binary-ho commented on src/main/java/domain/WinningNumbers.java
> +public class WinningNumbers implements Numbers {
추상 클래스로 바꿔 보았습니다! 감사합니다!

2023-02-18 06:28 UTC, binary-ho commented on src/main/java/dto/LottoResultDto.java
> +	}
LottoResultDto에서는 LottoNumbersDto와 달리  결과 출력문을 만들기 위해 OutputView 단에서 처리해줘야 할 것이 많았습니다. 
이를 LottoResultDto에서 처리해준다면, 출력 결과와의 의존성이 너무 높아질 수도 있을 것 같아, lottoResult에 대한 getter를 제공하고, View 단에서 출력문과 관련된 처리들을 진행하도록 했습니다.

2023-02-18 06:29 UTC, binary-ho commented on src/main/java/controller/LottoController.java
> +	private static final int LOTTO_TICKET_PER_PRICE = 1000;
말씀주신 내용은 잘 생각해보지 못 한 부분입니다.
섬세하게 알려주셔서 너무 감사합니다!

2023-02-18 06:30 UTC, binary-ho commented on src/main/java/view/OutputView.java
> +		if (winningAmount == 30000000) {
`30000000`의 액수를 가진 Enum 객체가 있는데 왜 이렇게 구현했는지 모르겠습니다.
아래바로 끊어 나타내는 방식 또한 몰랐습니다.
전부 반영했고, 앞으로 잘 사용하겠습니다. 알려주셔서 정말 감사합니다!

2023-02-18 07:05 UTC, binary-ho commented on src/main/java/view/OutputView.java
> +		EnumMap<Ranking, Integer> rankingResults = lottoResultDto.getLottoResult();
Enum을 사용할 때 EnumMap을 사용하는 것과 HashMap을 사용하는 것의 차이는 내부에 key-value를 저장하는 방식에서 옵니다.

HashMap은 이름대로 해시 테이블을 운용하며, 해싱된 key를 내부 버킷 하나에 매핑하여 value들을 연결 리스트와 같은 자료구조에 주렁주렁 달아가며 저장합니다.
그리고 EnumMap은 Enum을 사용하기 위해 최적화된 Map으로 내부적으로 key 값들을 배열에 저장합니다. 클래스가 운용할 열거 상수의 갯수가 정해져 있으므로, 열거 상수의 갯수에 맞는 사이즈에 배열을 만들어 관리합니다. 
덕분에 탐색시간은 O(1)에 가깝고, 최대한 적은 메모리를 사용합니다.

물론 HashMap 또한 해쉬 테이블을 사용하므로 정말 빠르지만, 버킷에 value들이 쌓이다 보면 시간 복잡도는 증가할 수 밖에 없습니다. 
또 불필요한 해싱 과정에 드는 시간이나, Iterator 없이 순회할 수 있다는 점도 장점입니다.

2023-02-18 07:22 UTC, binary-ho commented on src/main/java/view/OutputView.java
> +		StringBuilder purchaseCountString = new StringBuilder()
문자열 연결시 단순 String끼리 이어주는 연산은 평방 시간에 육박하는 시간복잡도를 가지고 있습니다.
이는 String이 불변이기 때문에, 합쳐주는 과정에서 전체 내용을 복사한 새로운 객체를 만들면서 발생합니다.

문자열을 이어주는 상황에서 StringBuilder의 append() 연산은 상수 시간만에 문자열을 이어줄 수 있습니다.
따라서 더 나은 성능을 위해 String 대신 StringBuiler를 사용했습니다.

2023-02-18 07:27 UTC, binary-ho commented on src/main/java/domain/LottoNumbers.java
> +	private static final int LOTTO_NUMBER = 6;
적절한 네이밍을 계속 고민했는데, 이렇게 좋은 이름이 있었군요
감사합니다!

2023-02-18 07:40 UTC, binary-ho commented on src/main/java/view/OutputView.java
> +			.forEach(System.out::println);
반영하겠습니다. 감사합니다!

Steam의 foreach는 Collection의 foreach와 달리 거대한 자료구조의 병렬 프로그래밍에 특화된 설계를 가지고 있습니다. 
Stream의 foreach는 애초에 아주 거대한 컬렉션을 다루기 위한 Stream에서 사용하는 반복문으로 Lazy한 연산을 위한 Loop Fusion이 일어납니다.  그래서 eager한 결과를 기대한 채 사용한다면 문제가 발생할 수도 있을것 같습니다.

이런 기능들이나 병렬 프로그래밍 혹은 stream의 다른 기능들이 딱히 필요 없는 경우에는 그냥 Collection의 foreach를 호출하는 것이 적절해 보입니다.

2023-02-19 13:09 UTC, skullkim commented on src/main/java/domain/LottoNumbers.java
> +public class LottoNumbers implements Numbers {
추상클래스로 바꾸는 것이 좋겠다는 의도가 아니였어요... 제가 설명을 잘 못한거 같네요.

지금 Numbers를 LottoNumbers와 WinningNumbers가 extends 하고 있죠? 이럴 때는 보통 다형성을 위해서 Numbers를 타입으로 사용하고 그 하위 클래스들을 타입으로 지정하지 않아요~. 그런대 코드를 보면 Numbers라는 클래스를 타입으로 사용하는 대신 WinningNumbers나 LottoNumbers를 직접적으로 사용하고 있어요.
예를 들어 Lotto의 generateLottoTicket()의 경우 List<LottoNumebrs> lottoNumbers 라는 코드를 사용하고 있네요.
상속 관계를 가진다면 List<Numbers>를 타입으로 사용하는 것이 더 적절하지 않을까요?

2023-02-19 13:19 UTC, skullkim commented on src/main/java/domain/LottoTicket.java
> +public class LottoTicket {
5천원어치 로또를 사면 나오는 로또 용지를 생각하셨다면 lottoTicket의 최대 크기가 5여야 한다는 검증이 포함되어야 하지 않나 싶네요. 

또 한, 모든 곳을 불변으로 만들어야 하는지도 고려해 보면 좋을 거 같아요. 불변은 상태을 원치 의도치 않게 바꾸지 않는 다는 장점이 존재하죠. 하지만 단점도 존재해요~. 이 단점들에 대해 찾아보시면 좋을 거 같아요!

마지막으로 객체지향 프로그래밍에서 객체를 나누는 이유에 대해서도 생각해 보시면 좋을 거 같아요.

2023-02-19 13:26 UTC, skullkim commented on src/main/java/dto/LottoNumbersDto.java
> +		return Numbers.toString();
그러면 DTO를 뷰 출력에 직접적으로 사용할 의도로 toString()을 재정의 한 것으로 보이는대요. DTO는 계층 간의 데이터 전달을 목적으로 사용되요. 따라서 진호님이 사용하신 것 처럼 뷰 출력을 위해 DTO의 toString()을 재정의 한다면 이는 DTO의 책임 범위를 벗어난 것으로 보이네요😅.

2023-02-19 13:28 UTC, skullkim commented on src/main/java/dto/LottoResultDto.java
> +	}
toString()을 재정의 하는 이유에 대해 생각해 보면 좋을 거 같네요. [이펙티브자바 Item12. toString을 항상 재정의하라](https://www.skullkim-dev.com/2022/05/08/Item-12.-toString%EC%9D%84-%ED%95%AD%EC%83%81-%EC%9E%AC%EC%A0%95%EC%9D%98%ED%95%98%EB%9D%BC/)를 읽어 보면 도움이 될거 같아요~.

2023-02-19 13:31 UTC, skullkim commented on src/main/java/domain/BonusBall.java
> +public class BonusBall {
BonusBall이 자기 자신에 대한 검증을 한다는 것은 좋은 생각인대요~. 이러면 올바르지 않은 값이 들어왔을 때 아예 인스턴스 생성이 안되서 잘못된 상태를 가진 인스턴스가 생성될 염려가 없기 때문이에요.
하지만, 검증에 사용될 범위를 외부에서 받는다면, 위에 말한 검증을 올바르게 할 수 없지 않을까요🧐? 보너스 볼 범위가 1~45인대 startNumber 값으로 -10을 준다면 어떻게 될까요?

2023-02-19 13:37 UTC, merged

2023-02-19 14:30 UTC, binary-ho commented on src/main/java/domain/LottoTicket.java
> +public class LottoTicket {
제가 말씀을 잘못 드렸네요.
로또 용지를 생각하고 만들었다는 의미는 
저희 미션의 경우엔 로또 용지 하나에 로또 번호들이 구매한 갯수만큼 적히는 상황을 생각하고 만들었다는 의미였습니다!

말씀주신 불변 객체의 단점과 객체를 나누는 이유에 대해서도 한번 찾아보겠습니다.

2023-02-19 14:57 UTC, binary-ho commented on src/main/java/domain/BonusBall.java
> +public class BonusBall {
설명 감사드립니다 좀 더 생각해보겠습니다!

2023-02-19 15:24 UTC, binary-ho commented on src/main/java/domain/LottoNumbers.java
> +public class LottoNumbers implements Numbers {
아닙니다. 말씀 잘 해주셨는데 제가 착각한 부분이 있습니다...
말씀 주신 부분 반영하겠습니다.
바쁘실텐데 섬세하게 리뷰 해주셔서 감사합니다!