[1단계 - 로또] 황의찬 미션 제출합니다.
hongik-dev-mentoring/java-lotto pull request #4
Opened 2023-02-10 06:19 UTC by euichaan

2023-02-11 12:21 UTC, dongho108 requested changes
안녕하세요 의찬님~ 반갑습니다. 👋

코드를 가독성있게 깔끔하게 작성해주셔서 읽기가 수월했습니다!

몇가지 코멘트 남겼으니 반영해주시고, 의견도 남겨주시거나 바로 DM 주셔도 좋습니다~! 화이팅~

2023-02-11 12:21 UTC, dongho108 commented on src/main/java/domain/WinningNumbers.java
> +	private static final int LOTTO_NUMBER = 6;
상수와 인스턴스의 위치를 구분해주면 가독성이 더 좋을 것 같아요~ 저는 상수를 먼저 선언해놓고 공백라인으로 인스턴스와 구분하는 방식으로 합니다~

```suggestion
	private static final int LOTTO_NUMBER = 6;

	private final List<Integer> winningNumbers;
```

2023-02-11 12:21 UTC, dongho108 commented on src/main/java/domain/WinningNumbers.java
> +	public boolean contains(Integer value) {
파라미터를 int가 아닌 Integer로 받은 이유가 있을까요? int로 받는것과 Integer로 받는것은 어떤 차이가 있을까요?

2023-02-11 12:21 UTC, dongho108 commented on src/main/java/domain/Lotto.java
> +		if (ranking == Ranking.THIRD && lottoNumbers.contains(bonusBall.getBonusBallNumber())) {
여기도 메서드로 빼면 가독성이 더 좋아보여요~
```suggestion
		if (isSecondRank()) {
```

2023-02-11 12:21 UTC, dongho108 commented on src/main/java/domain/Lotto.java
> +		List<Integer> pickNumber = winningNumbers.getNumbers();
이 메서드가 하는 역할 (랭크를 계산해서 랭크를 반환)과 check~ 로 시작하는 메서드명이 어색하다고 느껴지는데요! 의찬님 생각은 어떤가요?

2023-02-11 12:21 UTC, dongho108 commented on src/main/java/domain/LottoNumberGenerator.java
> +		List<Integer> pickNumbers = IntStream.range(startNumber, endNumber)
메서드명은 `pickNumber()` 인데 반환은 Numbers로 하고있네요?.?
```suggestion
	public LottoNumbers pickNumbers() {
```

2023-02-11 12:21 UTC, dongho108 commented on src/main/java/domain/LottoNumberGenerator.java
> +	}
여기는 한 줄이고 이름도 분명해서 굳이 메서드로 뺴지 않아도 될 것 같은데 의찬님 생각은 어떤가요?

2023-02-11 12:21 UTC, dongho108 commented on src/main/java/domain/LottoNumbers.java
> +		}
로또 번호의 길이는 잘 바뀌지 않을 것 같다는 비즈니스 규칙이 있지만, 만약 로또 길이가 달라진다면 변경포인트가 예외메세지까지 될 수 있겠네요.. 사람 일은 모르는거잖아요? ㅋㅎ

2023-02-11 12:21 UTC, dongho108 commented on src/main/java/domain/Numbers.java
> +
Numbers를 추상클래스가 아닌 인터페이스로 묶으신 이유가 있을까요? 이 둘의 사용차이도 알려주실 수 있을까요?

2023-02-11 12:21 UTC, dongho108 commented on src/main/java/domain/Numbers.java
> +}
여기 파라미터의 타입을 int가 아닌 Integer로 두신 특별한 이유가 있을까요?

2023-02-11 12:21 UTC, dongho108 commented on src/main/java/domain/Lotto.java
> +		}
rank를 결정하는게 lotto의 역할일까요?

2023-02-11 12:21 UTC, dongho108 commented on src/main/java/util/calculator/TotalPrizeCalculator.java
> +
util 패키지에 위치해있는 클래스들은 어느 패키지에서도 접근해 사용할 수 있게 하는 라이브러리같은 성질을 지니고 있다는 의미인데요,
그래서 "총 상금" 같은 도메인과 관련된 특정한 클래스는 util 패키지에 있는 것이 적합하지 않다고 생각해요~ 의찬님 생각은 어떠신가요?

2023-02-11 12:21 UTC, dongho108 commented on src/main/java/domain/Ranking.java
> +	FIRST(6, 2000000000), SECOND(5, 30000000), THIRD(5, 1500000),
아무래도 0이 많아지면 읽기 어렵고, 실수할 가능성도 높아지겠죠? Underscores in Numeric Literals(https://docs.oracle.com/javase/7/docs/technotes/guides/language/underscores-literals.html) 문서를 읽고 적용해 보아요!

2023-02-11 12:21 UTC, dongho108 commented on src/main/java/util/convertor/PurchaseAmountConvertor.java
> +	}
util 패키지에 위치해있는 클래스들에게서 도메인 규칙이 포함된 코드가 있는지 전체적으로 확인할 필요가 있을 것 같아요~

2023-02-11 12:21 UTC, dongho108 commented on src/main/java/view/OutputView.java
> +		List<Ranking> rankings = Arrays.stream(rankingValues)
배열을 지양하고 리스트를 쓰도록 하는게 좋은데요. 이 코드에선 굳이 두 줄로 나눌 필요는 없을 것 같아요!
```suggestion
		List<Ranking> rankings = Arrays.stream(Ranking.values())
```

2023-02-11 12:21 UTC, dongho108 commented on src/main/java/view/OutputView.java
> +import dto.LottoResultDto;
view에서 domain을 직접 의존하고 있네요!

2023-02-11 12:21 UTC, dongho108 commented on src/test/java/domain/LottoNumberGeneratorTest.java
> +	}
개인적으론 테스트코드에서는 모든 상수를 굳이 매직넘버로 뺄 필요는 없다고 생각해요~
해당 테스트만 보고도 어떤 테스트를 하고있는지 확인할 수 없고 `PICK_NUMBERS`가 무엇인지 확인하러 올라가야 하니까요!
의찬님은 어떻게 생각하시나요?

2023-02-11 12:21 UTC, dongho108 commented on src/test/java/domain/LottoTest.java
> +		LottoNumberGenerator lottoNumberGenerator = new LottoNumberGenerator(START_NUMBER, END_NUMBER, PICK_NUMBERS);
`입력하면` 이라는 행위를 `lotto`가 알고있을까요?

2023-02-11 12:21 UTC, dongho108 commented on src/test/java/domain/LottoTest.java
> +		LottoNumberGenerator lottoNumberGenerator = new LottoNumberGenerator(START_NUMBER, END_NUMBER, PICK_NUMBERS);
`임의로` 라는 단어가 어떤 기준인지 모호하게 느껴져요. 이 테스트는 그냥 당첨결과를 받을 수 있는지 확인하는 테스트인건가요?

2023-02-11 12:21 UTC, dongho108 commented on src/test/java/util/convertor/PurchaseAmountConvertorTest.java
> +
이 공백라인이 있는 이유가 있을까요?

2023-02-11 12:21 UTC, dongho108 commented on src/test/java/util/convertor/PurchaseAmountConvertorTest.java
> +
여기도요!

2023-02-13 11:41 UTC, euichaan commented on src/test/java/util/convertor/PurchaseAmountConvertorTest.java
> +
마찬가지로 필요없는 공백을 지우고 커밋하겠습니다!

2023-02-13 11:41 UTC, euichaan commented on src/test/java/util/convertor/PurchaseAmountConvertorTest.java
> +
필요없는 공백을 지우고 커밋하겠습니다!

2023-02-13 11:55 UTC, euichaan commented on src/main/java/domain/WinningNumbers.java
> +	private static final int LOTTO_NUMBER = 6;
제가 클린 코드 10장을 지키지 않았었네요😂

private static이 우선하고, 비공개 인스턴스 변수가 오는 순서가 맞는 것 같습니다.
다른 클래스에서도 모두 적용시키겠습니다.

2023-02-13 12:27 UTC, euichaan commented on src/main/java/domain/WinningNumbers.java
> +	public boolean contains(Integer value) {
Integer 는 int primitive 타입을 객체로 다루기 위해 사용하는 Wrapper class입니다.

Integer는 null을 허용하기 때문에 파라미터를 int로 받아야 하는 것이 맞는 것 같습니다.

2023-02-13 12:36 UTC, euichaan commented on src/main/java/domain/Lotto.java
> +		if (ranking == Ranking.THIRD && lottoNumbers.contains(bonusBall.getBonusBallNumber())) {
메서드로 분리 후 커밋하겠습니다! 확실히 가독성이 좋아졌습니다.👍

2023-02-13 12:43 UTC, euichaan commented on src/main/java/domain/Numbers.java
> +}
Integer 는 int primitive 타입을 객체로 다루기 위해 사용하는 Wrapper class입니다.

Integer는 null을 허용하기 때문에 파라미터를 int로 받아야 하는 것이 맞는 것 같습니다.

Integer -> int 로 수정한 후 커밋하겠습니다!

2023-02-13 12:51 UTC, euichaan commented on src/main/java/domain/Lotto.java
> +		List<Integer> pickNumber = winningNumbers.getNumbers();
메서드의 역할에 따라 `calculateRank`라는 이름으로 바꿔주었습니다!

2023-02-13 13:11 UTC, pine14 commented on src/main/java/domain/LottoNumberGenerator.java
> +		List<Integer> pickNumbers = IntStream.range(startNumber, endNumber)
메서드명을 `generateLottoNumbers` 라고 변경했습니다.

2023-02-13 13:27 UTC, euichaan commented on src/main/java/domain/LottoNumberGenerator.java
> +	}
`Collections.shuffle`과 `Collections.sort`를 메서드로 빼지 않고 리팩터링 한 후 결과를 살펴봤는데,
Collections.shuffle 과 Collections.sort 메서드 이름만으로 하는 일을 잘 나타낼 수 있을 것 같아서 메서드로 빼지 않아도 될 것 같습니다.

2023-02-13 14:05 UTC, euichaan commented on src/main/java/domain/LottoNumbers.java
> +		}
일급 컬렉션을 만들 때
- 6개의 숫자로만 이루어지고
- 6개의 숫자들은 서로 중복이 없는
자료구조가 없어서 LottoNumbers 클래스를 만든 것이긴 한데, 예외 메시지를 로또 번호가 7개, 8개로 이루어진다면 예외메시지까지 변경점이 될 수 있다는 말은 맞는 것 같습니다.

일단 생각나는 방법으로 예외 메시지를 상수로 처리해서 변경에 용이하게는 만들었는데, 더 좋은 방법이 있을까요?

2023-02-13 14:12 UTC, euichaan commented on src/main/java/domain/Ranking.java
> +	FIRST(6, 2000000000), SECOND(5, 30000000), THIRD(5, 1500000),
좋은 기능이 있었군요! 적용 완료했습니다.👍

2023-02-13 14:18 UTC, euichaan commented on src/main/java/domain/Numbers.java
> +
추상 클래스와 인터페이스는 하는 일은 비슷합니다.
**추상 클래스와 인터페이스는 상속받는 클래스 혹은 구현하는 인터페이스 안에 있는 추상 메서드를 구현하도록 강제합니다.**

존재 목적은 다릅니다. 추상 클래스는 상속받아서 기능을 이용하고, 확장시키는 데 있습니다.
반면 인터페이스는 함수의 껍데기만 있는데, 그 이유는 그 함수의 구현을 강제하기 위해서입니다.
구현을 강제함으로써 구현 객체의 같은 동작을 보장할 수 있습니다.

로또 미션에서 로또 숫자와 당첨 번호는 같은 형태를 가지고 있습니다 (6개의 숫자, 중복 없음)
따라서 `LottoNumbers`와 `WinningNumbers`의 같은 동작을 보장하기 위해, 인터페이스로 묶었습니다.

2023-02-13 14:20 UTC, euichaan commented on src/main/java/view/OutputView.java
> +		List<Ranking> rankings = Arrays.stream(rankingValues)
리팩터링 완료했습니다!

2023-02-14 02:17 UTC, euichaan commented on src/main/java/util/calculator/TotalPrizeCalculator.java
> +
다른 util 클래스와 달리 비즈니스 로직이 맞는 것 같습니다.

도메인 패키지로 이동 후 메서드 이름도 수정했습니다.

2023-02-14 03:36 UTC, euichaan commented on src/main/java/domain/Lotto.java
> +		}
rank 를 결정하는 책임을 따로 `RankDiscriminator` 로 분리했습니다.

lotto에서 rank를 결정하는 메서드들을 전부 지우고, 그 책임을 위임했습니다.

2023-02-14 05:48 UTC, euichaan commented on src/main/java/util/convertor/PurchaseAmountConvertor.java
> +	}
`PurchaseAmountConvertor` 클래스와 `WinningNumberConvertor` 클래스를 도메인 패키지로 이동했습니다.

2023-02-14 11:49 UTC, euichaan commented on src/main/java/view/OutputView.java
> +import dto.LottoResultDto;
`RankDto` 클래스를 만들어 view에서 domain을 직접 의존하는 것을 막아줬습니다.

여러가지 방법으로 시도해봤는데, 
1.RankView 클래스를 만들어 랭킹과 관련된 것들을 모아서 OutputView에서 출력할 때 사용
2.EnumMap<Rank, Integer> 를 순서가 보장되는 LocalHashMap<String, Integer> 로 변환 후 출력할 때 처리

어떤 것이 더 좋은 방법일까요? 🤔

2023-02-14 12:03 UTC, euichaan commented on src/test/java/domain/LottoTest.java
> +		LottoNumberGenerator lottoNumberGenerator = new LottoNumberGenerator(START_NUMBER, END_NUMBER, PICK_NUMBERS);
rank를 결정하는 것을 lotto에서 `RankDiscriminator` 클래스로 옮기면서 삭제했습니다!

2023-02-14 12:04 UTC, euichaan commented on src/test/java/domain/LottoTest.java
> +		LottoNumberGenerator lottoNumberGenerator = new LottoNumberGenerator(START_NUMBER, END_NUMBER, PICK_NUMBERS);
rank를 결정하는 것을 lotto에서 `RankDiscriminator` 클래스로 옮기면서 삭제했습니다!

2023-02-14 12:13 UTC, euichaan commented on src/test/java/domain/LottoNumberGeneratorTest.java
> +	}
https://softwareengineering.stackexchange.com/questions/322716/are-magic-numbers-acceptable-in-unit-tests-if-the-numbers-dont-mean-anything

를 보면 매직 넘버를 테스트에 사용해도 괜찮냐는 글이 많았는데, 제 생각은 상수를 사용하는 것이 좋은 것 같습니다.
하지만 때에 따라서는 매직 넘버를 사용하는 것이 테스트 **가독성을 높인다면**, 매직 넘버를 사용할 수도 있을 것 같습니다.

무조건 매직 넘버 대신 상수를 사용해야 한다고 알고 있었는데, 테스트 코드에서는 예외가 있을 수 있다는 사실을 알게 되었네요!

2023-02-16 01:27 UTC, dongho108 approved these changes
로또 1단계 하느라 고생 많으셨습니다~~!!
몇가지 코멘트를 더 남겼는데요, 일단 2단계를 위해 1단계는 여기서 머지하고 추가로 달아드린 코멘트는 2단계를 진행하며 반영해주시면 감사하겠습니다!

2단계에서 뵙겠습니다!

2023-02-16 01:27 UTC, dongho108 commented on src/main/java/domain/Rank.java
> +	}
쓰이는 곳이 없는 메서드 같아요!

2023-02-16 01:27 UTC, dongho108 commented on src/main/java/domain/Rank.java
> +		}
인덴트가 2인데 1로 줄여볼 수 있을까요?

2023-02-16 01:27 UTC, dongho108 commented on src/main/java/domain/RankDiscriminator.java
> +		List<Integer> prizeNumbers = winningNumbers.getNumbers();
bonusBall은 안쓰이는 변수니까 제거해줄까요?

2023-02-16 01:27 UTC, dongho108 commented on src/main/java/domain/Rank.java
> +	}
얘도 안쓰이는 메서드네요!

2023-02-16 01:27 UTC, dongho108 commented on src/main/java/domain/BonusBall.java
> +	private static final int MAX_LOTTO_NUMBER = 45;
1~45 규칙이 보너스볼에도 있고 LottoNumberGenerator에도 있는데 LottoNumber라는 객체로 책임을 주는 건 어떨까요?

2023-02-16 01:27 UTC, dongho108 commented on src/main/java/controller/LottoController.java
> +
안쓰이는 임포트는 제거해주세요~ save actions의 optimize import 옵션을 사용하면 더 편리하답니다

2023-02-16 01:27 UTC, dongho108 commented on src/main/java/domain/Lotto.java
> +	}
정적팩터리메서드패턴을 사용하신 것 처럼 보이네요~ 메서드 선언순서는 생성자 다음에 static 메서드를 배치해주세요~

2023-02-16 01:36 UTC, merged

2023-02-17 04:14 UTC, euichaan commented on src/main/java/domain/Rank.java
> +	}
불필요한 메서드를 제거 후 커밋하겠습니다!

2023-02-17 04:14 UTC, euichaan commented on src/main/java/domain/Rank.java
> +	}
불필요한 메서드를 제거 후 커밋하겠습니다!

2023-02-17 04:48 UTC, euichaan commented on src/main/java/domain/Rank.java
> +		}
```java
public static Rank findRank(int correctNumber, boolean bonus) {
	return Arrays.stream(Rank.values())
		.filter(getRank(correctNumber, bonus))
		.findAny()
		.orElse(UNRANKED);
}

private static Predicate<Rank> getRank(int correctNumber, boolean bonus) {
	return rank -> rank.getCorrectNumber() == correctNumber
		&& rank.isBonus() == bonus;
}
```
다음과 같이 스트림을 사용해서 인덴트를 줄이고 메서드를 분리해 가독성을 높였습니다.

2023-02-17 04:49 UTC, euichaan commented on src/main/java/domain/RankDiscriminator.java
> +		List<Integer> prizeNumbers = winningNumbers.getNumbers();
불필요한 변수를 제거 후 커밋하겠습니다.

2023-02-17 04:51 UTC, euichaan commented on src/main/java/controller/LottoController.java
> +
좋은 옵션이 있었네요! 제거했습니다.

2023-02-17 04:56 UTC, euichaan commented on src/main/java/domain/Lotto.java
> +	}
수정 완료했습니다!

2023-02-20 09:36 UTC, pine14 commented on src/main/java/domain/BonusBall.java
> +	private static final int MAX_LOTTO_NUMBER = 45;
LottoNumber라는 객체로 책임을 준 후,
BonusBall은 LottoNumber을 필드로 가지고 있게 구현했습니다(composition).