[2단계 - 로또] 김경근 미션 제출합니다.
hongik-dev-mentoring/java-lotto pull request #6
Opened 2023-02-18 14:50 UTC by JuneK3

2023-02-20 02:27 UTC, dongho108 requested changes
안녕하세요 경근님 ㅎㅎ
2단계 미션 빠르게 제출해주셨네요!

이번 미션도 잘 구현해주셔서 좀 더 높은 난이도의 코멘트를 드릴 수 있었습니다.
리뷰 반영하시다가 어려운 개념이나 이해가 안된다면 언제든지 다시 물어봐주세요!

2023-02-20 02:27 UTC, dongho108 commented on src/test/java/domain/DuplicateLottoNumbersRemoverTest.java
> +        );
각 테이터 만들어주는 부분들을 메서드로 분리하면 가독성이 더 좋을 것 같아요~
```suggestion
        List<LottoNumbers> manualLottoNumbersGroup = 메서드명();
        List<LottoNumbers> autoLottoNumbersGroup = 메서드명();
        
        // when
        DuplicateLottoNumbersRemover.removeDuplicates(manualLottoNumbersGroup, autoLottoNumbersGroup);
        
        // then
        LottoNumbers lottoNumbers = new LottoNumbers(Stream.of(1, 2, 3, 4, 5, 6)
                .map(LottoNumber::new)
                .collect(Collectors.toList())
        );
```

2023-02-20 02:27 UTC, dongho108 commented on src/test/java/domain/DuplicateLottoNumbersRemoverTest.java
> +        assertThat(autoLottoNumbersGroup.get(0).equals(lottoNumbers)).isFalse();
assertAll로 묶어줄까요?

2023-02-20 02:27 UTC, dongho108 commented on src/test/java/domain/LottoNumbersGroupCombinerTest.java
> +    public void combineTest() {
위에서 만든 메서드를 재사용해서 여기도 간단하게 만들 수 있겠네요!

2023-02-20 02:27 UTC, dongho108 commented on src/main/java/domain/LottoNumbersAutoGenerator.java
> +public class LottoNumbersAutoGenerator {
로또 넘버는 1~45 사이에서만 생성되니까 1~45 사이의 숫자를 매번 생성하는 것보다 1~45개 숫자 만큼의 로또넘버를 미리 만들어두고 셔플하고 재사용하는 방식은 어떨까요?

LottoNumber가 VO로 사용되고 있어서 값만 같으면 같은 객체라고 인식도 할 수 있으니까요~

2023-02-20 02:27 UTC, dongho108 commented on src/main/java/domain/DuplicateLottoNumbersRemover.java
> +        for (LottoNumbers autoLottoNumbers : autoLottoNumbersGroup) {
List<LottoNumbers> 라는 개념이 자주사용되고 있는데요, 한 장의 티켓안에 여러 줄의 로또 넘버들이 있는 개념이 또 존재해서 그렇지 않을까요?
LIst<LottoNumbers>를 가지는 새로운 일급컬렉션에 책임을 줄 수 있을 것 같아요.
경근님 생각은 어떠신가요?

2023-02-20 03:15 UTC, JuneK3 commented on src/test/java/domain/DuplicateLottoNumbersRemoverTest.java
> +        );
테스트 코드에서도 메소드 분리로 가독성을 개선할 수 있다는 점을 망각했네요..
메소드로 분리해서 개선해보겠습니다.

2023-02-20 03:15 UTC, JuneK3 commented on src/test/java/domain/DuplicateLottoNumbersRemoverTest.java
> +        assertThat(autoLottoNumbersGroup.get(0).equals(lottoNumbers)).isFalse();
넵 수정하겠습니다.

2023-02-20 03:23 UTC, JuneK3 commented on src/test/java/domain/LottoNumbersGroupCombinerTest.java
> +    public void combineTest() {
한번 수정해보겠습니다.

2023-02-20 03:29 UTC, JuneK3 commented on src/main/java/domain/LottoNumbersAutoGenerator.java
> +public class LottoNumbersAutoGenerator {
확실히 generate 메소드를 호출할때마다 1부터 45사이의 숫자를 생성하지 않아도 되니까 더 좋은 것 같아요.
말씀해주신대로 개선해보겠습니다.

2023-02-20 03:51 UTC, JuneK3 commented on src/main/java/domain/DuplicateLottoNumbersRemover.java
> +        for (LottoNumbers autoLottoNumbers : autoLottoNumbersGroup) {
확실히 List<LottoNumbers>가 자주 사용되는 것 같습니다.
LottoTicket이라는 일급컬렉션을 도입해 관련 메소드들을 가지도록 하는게 더 좋을 것 같아요.
말씀해주신대로 수정해보겠습니다.

2023-02-20 05:33 UTC, JuneK3 commented on src/main/java/domain/DuplicateLottoNumbersRemover.java
> +        for (LottoNumbers autoLottoNumbers : autoLottoNumbersGroup) {
일단 LottoTicket가 ticket combine 기능만 담당하도록 했습니다.
중복된 LottoNumbers를 제거하고 새로 generate하는 기능까지 담당하는 것도 고민해봤는데
LottoTicket 인스턴스에서 removeDuplicates 메소드를 호출하는 방식의 경우 제가 전달하고 싶었던 메소드의 의도가 제대로 전달되지 않는 것 같았어요. 물론 제가 좋은 코드를 작성하지 못한게 원인이겠지만 메소드가 어떤 역할을 하는지 이해하기 어렵다는 느낌을 받았습니다.
LottoTicket이 중복제거 기능까지 담당하게 되면 필요 이상의 책임을 가지게 되는 것 같아서 분리하는 방식을 유지했습니다. 일단 제가 생각한 방식대로 수정해봤는데 의도하신 방향으로 진행한건지 잘 모르겠네요..

2023-02-21 14:56 UTC, dongho108 commented on src/main/java/domain/DuplicateLottoNumbersRemover.java
> +        for (LottoNumbers autoLottoNumbers : autoLottoNumbersGroup) {
`LottoTicket`이 생성될때 필요한 어떤 검증이라던지 `List<LottoNumbers>`를 다루는 책임이 있다면 `LottoTicket`에 들어가면 좋을 것 같아요
generate는 따로 책임을 가지고있는 친구가 있으니 지금도 괜찮습니다~

2023-02-21 14:58 UTC, dongho108 approved these changes
경근님 로또미션 하느라 고생 정말 많으셨습니다.

1단계에서 얼마나 기반을 잘 다져놨냐에 따라서 2단계 미션이 쉬워질 수 있고 어려워질 수 있었던 것 같아요.
그런 면에서 경근님 열심히 해주셔서 미션 잘 마무리가 되었네요.

4주동안 정말정말 고생 많으셨습니다.
앞으로도 학교에서 자주뵙고 인사하며 지내요~!

2023-02-21 14:58 UTC, merged

2023-02-22 02:05 UTC, JuneK3 commented
동호님도 4주동안 고생 많으셨습니다.
항상 이해하기 쉽게 자세히 리뷰해주셔서 도움이 많이 되었어요.
덕분에 많이 배웠습니다. 같은 수업 듣게 되면 얼굴 자주 볼 수 있겠네요.
개강하고 학교에서 뵐게요.