[2단계 - 로또] 황의찬 미션 제출합니다.
hongik-dev-mentoring/java-lotto pull request #7
Opened 2023-02-19 02:21 UTC by euichaan

이번 미션에서 진행한 변경점은 다음과 같습니다.

**1. 1부터 45라는 로또 번호 번호의 규칙을 LottoNumber 클래스에 옮긴다.**
SRP원칙에 따라 로또 번호 범위가 변경되었을 때 LottoNumber 클래스를 열어볼 것이라고 생각해서 여러 곳에 퍼져있던 로또 번호 범위에 대한 책임을 LottoNumber 클래스로 옮겼습니다.

**2. 수동과 자동 번호를 생성하는 NumbersGenerator 인터페이스를 만든 후 실행 시점에 결정한다.**
**3. Convertor를 이용하지 않고 InputView에도 책임을 준다.**

2023-02-20 04:42 UTC, dongho108 requested changes
의찬님 2단계 구현도 너무 잘해주셨네요 ㅎㅎ

가독성도 너무 좋아지고 읽기 쉬운 코드가 된 것 같아요!
몇가지 코멘트 남겼는데 생각해보시거나 반영해보시고 궁금하거나 어려운거 있으시면 언제든지 DM 주시면 됩니다.

이제 얼마 안남았는데 화이팅!!

2023-02-20 04:42 UTC, dongho108 commented on src/main/java/controller/LottoController.java
> +	private Lotto autoLotto;
만약 현재 프로그램이 콘솔이 아니라 웹 기반이라고 가정해보면
main메서드에서 새로운 컨트롤러를 매번 생성할때 어떤 문제가 발생할 수 있을까요?

2023-02-20 04:42 UTC, dongho108 commented on src/main/java/controller/LottoController.java
> +		autoLotto = getAuttoLottos(autoLottoCount);
Lotto는 인터페이스에만 의존하고, 생성 방법에 대한 구현체를 외부에서 주입해주는 방식 너무 좋습니다. 💯

2023-02-20 04:42 UTC, dongho108 commented on src/main/java/util/generator/NumbersGenerator.java
> +}
util 패키지에서 domain을 알고있네요.
인터페이스 명은 NumbersGenerator 이지만 메서드에서 Lotto의 존재를 알고있어요!

이해하기 쉽게 예를 들어서 설명드리면, 저희가 java.util.List 를 쓸때 이 List가 저희 도메인인 Lotto나 rank를 알고있진 않잖아요?
그리고 어떤 개발자든 저 List를 꺼내서 쓸 수 있고요.

저희의 util 클래스도 마찬가지 입니다. 어떤 도메인이든 꺼내서 사용할 수 있도록 만들어야해요.

그런데 만약 우리 domain과 관련된 util클래스들이라면 저는 domain 패키지 내에서 util패키지를 만들고 거기에 넣어볼 생각도 할 수 있을 것 같아요 ㅎㅎ

2023-02-20 04:42 UTC, dongho108 commented on src/main/java/util/generator/RandomLottoNumberGenerator.java
> +
저희 LottoNumber 1~45의 숫자이고, 어차피 VO로 사용되고 있다면 매번 랜덤으로 생성하기보단 1~45개의 로또넘버를 미리 만들어놓고 재사용해볼 수도 있지 않을까요?

2023-02-20 04:42 UTC, dongho108 commented on src/main/java/view/OutputView.java
> +	private static final String MANUAL_PURCHASE_MESSAGE = "수동으로 구매할 번호를 입력해 주세요.";
안쓰이는 상수인거같아요!

2023-02-20 04:42 UTC, dongho108 commented on src/main/java/dto/LottoNumbersDto.java
이 클래스에 있는 toString은 어떤 용도로 사용되고 있을까요?

2023-02-20 10:29 UTC, euichaan commented on src/main/java/view/OutputView.java
> +	private static final String MANUAL_PURCHASE_MESSAGE = "수동으로 구매할 번호를 입력해 주세요.";
제거 후 커밋했습니다!

2023-02-20 11:10 UTC, euichaan commented on src/main/java/util/generator/RandomLottoNumberGenerator.java
> +
static 초기화 블록에서 IntStream 을 이용해서 45개의 로또넘버를 미리 만들어두었습니다.

2023-02-20 11:11 UTC, euichaan commented on src/main/java/controller/LottoController.java
> +		autoLotto = getAuttoLottos(autoLottoCount);
감사합니다 ㅎㅎ

2023-02-20 11:16 UTC, euichaan commented on src/main/java/dto/LottoNumbersDto.java
수동으로 생성된 로또 티켓과 자동으로 생성된 로또 티켓을 출력할 때 사용하는 용도로 사용합니다.
List의 toString은 [] 안에 리스트의 아이템들이 추가되어, 요구사항처럼 로또를 출력할 수 있었습니다.

2023-02-20 13:08 UTC, euichaan commented on src/main/java/util/generator/NumbersGenerator.java
> +}
도메인과 관련된 클래스들을 util 패키지에서 이동하는 것이 필요하겠군요! 

List로 비유하신 설명이 이해가 잘 되었습니다. 감사합니다.

2023-02-20 13:25 UTC, pine14 commented on src/main/java/controller/LottoController.java
> +	private Lotto autoLotto;
인스턴스를 매번 생성하므로 메모리 낭비가 심합니다.
고객 트래픽이 초당 100이 나온다면, 초당 100개 객체가 생성되고 소멸될 것입니다.

**해결방안은 해당 객체가 딱 1개만 생성되고, 공유하도록 설계하면 됩니다.**

컨트롤러를 싱글톤으로 만들고 인스턴스 변수를 없애는 방식으로 구현해보겠습니다.

2023-02-21 15:00 UTC, dongho108 commented on src/main/java/controller/LottoController.java
> +	private Lotto autoLotto;
💯

2023-02-21 15:54 UTC, dongho108 approved these changes
의찬님 로또미션 진행하느라 너무너무 고생 많으셨습니다!! 🥇 
의찬님 코드는 항상 고민이 많이 담긴 코드라는게 티가 많이 났습니다.
실제로도 고민을 많이하시고, 질문도 많이하시고, 책도 많이 읽으셨는데 이런 시간들이 다 코드에 담겨있던 것 같아요.

4주동안 정말 열심히 하셨고 앞으로도 잘해낼거라고 믿습니다.
너무 고생많으셨습니다!

2023-02-22 05:02 UTC, merged