[2단계 - 로또] 이태순 미션 제출합니다.
hongik-dev-mentoring/java-lotto pull request #9
Opened 2023-02-21 06:21 UTC by LTSGOD

2023-02-22 04:44 UTC, skullkim requested changes
태순님~ 피드백 반영 부탁해요!. 그리고 일부 도메인 객체에 대한 테스트가 없는대 어떤 이유로 테스트를 작성하지 않으신건가요?

2023-02-22 04:44 UTC, skullkim commented on src/main/java/domain/LottoGenerator.java
> +    public static void manualLottoNumberGenerator(int manualLottoNum, List<LottoNumbers> lottoNumbersGroup) {
메서드 이름은 동사나 동사구를 사용해 주세요. 그리고 도메인에서 뷰를 호출하고 있네요. 이러면 어떤 문제가 발생할까요?

2023-02-22 04:44 UTC, skullkim commented on src/main/java/domain/LottoNumbers.java
> +    private static final int LOTTO_PRICE = 1000;
객체와 자료구조는 어떤 차이가 있을까요?

2023-02-22 04:44 UTC, skullkim commented on src/test/java/domain/LottoCheckerTest.java
> +        assertThat(resultMap.get(LottoPrize.PRIZE_1ST)).isEqualTo(1);
여러개의 assert문을 그냥 사용했을 때와 assertAll()로 묶었을 때 차이는 뭘까요? 어느 것을 사용하는 것이 더 좋을까요?

2023-02-25 04:08 UTC, LTSGOD commented on src/test/java/domain/LottoCheckerTest.java
> +        assertThat(resultMap.get(LottoPrize.PRIZE_1ST)).isEqualTo(1);
assert문을 단독 사용하면 실패시 모든 테스트가 중지되는데 assertAll은 모든 assert문의 실패결과를 볼 수있는 것 같아요. assertAll문으로 묶어줘서 모든 assert문의 결과를 보는 것이 더 좋을 것 같습니다!

2023-02-25 04:56 UTC, LTSGOD commented on src/main/java/domain/LottoGenerator.java
> +    public static void manualLottoNumberGenerator(int manualLottoNum, List<LottoNumbers> lottoNumbersGroup) {
도메인이 뷰를 호출하면 유지보수하기 어렵고 나중에 수정하기 어려운 코드가 되는 문제가 발생하는 것 같습니다. 수정하겠습니다.

2023-02-25 05:18 UTC, LTSGOD commented on src/main/java/domain/LottoNumbers.java
> +    private static final int LOTTO_PRICE = 1000;
객체는 캡슐화를 통해 data를 메서드로  다루고 자료구조는 따로 캡슐화를 하지 않고 직접적으로 데이터에 접근하는 차이점이 있는게 맞을까요??

2023-02-25 05:33 UTC, LTSGOD commented
앗 테스트코드 짜는 것을 놓친것 같습니다.....! 테스트 코드 추가하겠습니다!

2023-02-26 06:20 UTC, merged